import Header from './Header';
import Styles from '@/styles/contact.module.css';
import IN from './../../../public/images/in.png'
import GM from './../../../public/images/gm.jpg'
import Image from 'next/image';
import Head from 'next/head';
const Contact = () => {
 return (
  <>
   <Head>
    <title>Contact</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/ty.ico" />
   </Head>
   <Header />
   <div className='wrapper'>
    <div className={Styles.container}>
     <h1>Contact Me</h1>
     <p>If you have any questions or feedback, please feel free to reach out at:</p>
     <ul>
      <li>
       

       <a href="mailto:thakaresagar86@gmail.com">thakaresagar86@gmail.com</a>

      </li>
      <br />
      <li>
       

       <a href="https://www.linkedin.com/company/example">LinkedIn</a>
      </li>
     </ul>
    </div>
   </div>
  </>
 );
};

export default Contact;
