import React from 'react'
import Link from 'next/link'
import Styles from '@/styles/Home.module.css'
import Image from 'next/image'
import welcome from '../../.././public/images/giphy.gif'
import Honest from "../../.././public/images/honest.jpg"
import Header from './Header.js'
import Footer from '././footer.js'
import Head from 'next/head'
const Home = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link rel="icon" href="/ty.ico" />
      </Head>
      <Header />

      <main className={Styles.main}>

        <div className={Styles.image}>
          <Image className={Styles.image} src={welcome} width={350} height={350} />
          <h1 className={Styles.h1} >Welcome to bug-catching Town!</h1>
        </div>

        <div className={Styles.p}>
          <p>
            As a passionate gamer, I have always been fascinated by the game development and testing. Over time, I have developed a talent for identifying and reporting bugs in games. Through hours of playing and testing, I have learned to thoroughly explore every aspect of games to uncover even the hardest-to-find issues.

            This portfolio is where I share my findings with the world, including fellow developers.</p>

          <p> I believe that gaming is a powerful medium that can bring people together, spark imagination, and create unforgettable experiences. By playing my part in finding and fixing bugs, I hope to contribute to the growth and success of the gaming industry.
          </p>

          <Image className={Styles.honest} src={Honest} width={450} height={350} />
        </div>
      </main>


    </>
  )
}

export default Home